name: chatty
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1



environment:
  sdk: '>=3.1.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # GetX
  get: ^4.6.5


  intl: ^0.18.1


  flutter_screenutil: ^5.9.0


  pull_to_refresh: ^2.0.0


  fluttertoast: ^8.2.2


  flutter_easyloading: ^3.0.5

  # http
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1


  shared_preferences: ^2.2.1
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1

  # SHA
  crypto: ^3.0.3

  # webView
  webview_flutter: ^4.2.4

  # loading
  loading_animations: ^2.2.0

  # share
  share_plus: ^7.1.0


  device_info_plus: ^9.0.3


  package_info_plus: ^4.1.0


  path_provider: ^2.1.1

  # permission
  permission_handler: ^10.4.4


  sentry: ^7.9.0


  uni_links: ^0.5.1


  flutter_spinkit: ^5.2.0

  flutter_swiper_view: ^1.1.8

  dots_indicator: ^3.0.0

  google_sign_in: ^6.1.5

  firebase_core: ^2.15.1

  firebase_messaging: ^14.6.7

  firebase_in_app_messaging: ^0.7.3+5

  firebase_auth: ^4.9.0

  cloud_firestore: ^4.9.1

  firebase_storage: ^11.2.6

  location: ^5.0.3

  image_picker: ^1.0.4

  photo_view: ^0.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true



  assets:
    - assets/
    - assets/images/
    - assets/icons/



  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf