// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXPJeCO13i4wuBd6tgZxooms4OYoq6T0I',
    appId: '1:401421682631:web:45389e4362dee775173be2',
    messagingSenderId: '401421682631',
    projectId: 'chatty-b80ba',
    authDomain: 'chatty-b80ba.firebaseapp.com',
    storageBucket: 'chatty-b80ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAar-epp3HANmu9mQ3IZvClSgNdjlUyCtw',
    appId: '1:401421682631:android:257f506734dedee7173be2',
    messagingSenderId: '401421682631',
    projectId: 'chatty-b80ba',
    storageBucket: 'chatty-b80ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUyhgZA8I6IfLpTzFbh6cvo12Iyp_8VFU',
    appId: '1:401421682631:ios:d37cb75ed4b70b92173be2',
    messagingSenderId: '401421682631',
    projectId: 'chatty-b80ba',
    storageBucket: 'chatty-b80ba.appspot.com',
    androidClientId: '401421682631-gnodb48u2tkmj4c1d5edm0e1h20b5f47.apps.googleusercontent.com',
    iosClientId: '401421682631-eas33256nfqd3ga2jh9h60ip7841tsk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUyhgZA8I6IfLpTzFbh6cvo12Iyp_8VFU',
    appId: '1:401421682631:ios:1e2ffa11818e9c8e173be2',
    messagingSenderId: '401421682631',
    projectId: 'chatty-b80ba',
    storageBucket: 'chatty-b80ba.appspot.com',
    androidClientId: '401421682631-gnodb48u2tkmj4c1d5edm0e1h20b5f47.apps.googleusercontent.com',
    iosClientId: '401421682631-13jumoh39hvqfsu4l07kdf84i9ofqoki.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatty.RunnerTests',
  );
}
